### ISSUE TITLE
TypeError: session.SetSortOrder is not a function

### ISSUE THREAD

**Issue by idanzhavi09** [sarakusha/novastar#612]
When trying to run the following code:
```
        const address = await net.findNetDevices();
        const session = await net.default.open(address[0]);
        session.connection.on('open' , async() => {
            const ctrl = new ScreenConfigurator(session);
            await ctrl.reload();
            const firstCardBrightness = await ctrl.ReadFirstBrightness();
            console.log(firstCardBrightness);
        })
```

I got an error saying

> TypeError: session.SetSortOrder is not a function

has anyone encountered this error ?

**Comment by sarakusha** [comment]
I was unable to reproduce the error in node REPL.
```js
node
> net = require('@novastar/net')
> ScreenConfigurator = require('@novastar/screen').default
> var addresses
> net.findNetDevices().then(a => { addresses = a })
> session = net.default.open(addresses[0])
> ctrl = new ScreenConfigurator(session)
> ctrl.reload()
> ctrl.ReadFirstBrightness().then(b => console.log('Ok', b), err => console.error(err))
```
But I can guess why there are "TypeError: x is not a function" errors.
Because of the sheer number of API methods, most of which you won't need, the ```session``` object doesn't support these methods out of the box. Instead, you must include the methods you need from  ```@novastar/native``` (described in readme @novastar/native). When using ```@novastar/screen```, all used modules should be loaded automatically, which, apparently, does not happen in your case.

**Comment by idanzhavi09** [comment]
first of all thank you for your help!
After implementing your solution I got another problem.
When creating the Session.ts file as specified in the `@novastar/native` readme file
I got an error saying "Module '"@novastar/codec"' has no exported member 'API'.ts(2305)"
I would very much appreciate your help.
